name: ngrok

instance_groups:
- name: ngrok
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks: [{name: default}]
  jobs:
  - name: ngrok
    release: ngrok
    properties:
      authtoken: ((1eG3fAsycx6lfgt7ZmH1Grvlzse_7VmbTGhwjKnvZA1vs6Gx1))
      config: |
        tunnels:
          myapp:
            proto: http
            addr: 8000
            subdomain: drnic-myapp

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3363.latest

releases:
- name: ngrok
  version: 1.0.0
  url: https://github.com/cloudfoundry-community/ngrok-boshrelease/releases/download/v1.0.0/ngrok-1.0.0.tgz
  sha1: e95f03eeed543fe3d020316afe1736763ec77ba5
