name: ngrok

instance_groups:
- name: ngrok
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks: [{name: default}]
  jobs:
  - name: ngrok
    release: ngrok
    properties:
      authtoken: ((ngrok-authtoken))
      config: |
        tunnels:
          myapp:
            proto: http
            addr: 8000
            subdomain: drnic-myapp

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3363.latest

releases:
- name: ngrok
  version: latest
